CREATE TABLE D_USER(
    ID INT(16) PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    QR_CODE VARCHAR(255) UNIQUE NOT NULL ,
    
    CREATED_ON DATETIME,
    MODIFIED_ON DATETIME
    
    );


CREATE TABLE D_LOG(
    ID INT(16) PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT(16),
    SEVERITY VARCHAR(255),
    MESSAGE VARCHAR(255),
   
    CREATED_ON DATETIME,
    MODIFIED_ON DATETIME,
    
    CONSTRAINT FK_USER
    FOREIGN KEY (USER_ID) REFERENCES D_USER(ID)
    );

