version: '2'
volumes:
    webapp-data:
    db-data:
services:
  web-app:
    restart: always
    build: ./webapp
    volumes:
      - 'webapp-data:/data'
    privileged: true
    ports:
      - 443:5000
  mysql:
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
        - 'db-data:/var/lib/mysql'
    ports:
        - '3306'
    environment:
        MYSQL_DATABASE: BALENA_DOOR_DB
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_USER: user
        MYSQL_PASSWORD: 12345
